version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: instashare
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - ./app:/app/app
        - ./specs:/app/specs
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:

