name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv pip install --system --no-cache-dir -r Backend/requirements.txt
      working-directory: Backend

    - name: Run tests
      run: pytest app/test/
      working-directory: Backend


